### PR TITLE
Tighten up the GUI layout, 

### PR DESCRIPTION
**Pull request by adesmet-ssec**
Tighten up the GUI layout:

- Only columns that make sense to stretch are allowed to stretch.
- Short tables (settings and filters) are compacted to the top.
- The section labels on the filters tab now overhang their settings, instead of being next to them.

Before|After
------|-----
|
|

### CODE REVIEW

**Comment by adesmet-ssec** [comment]
**Warning:** If merged with #18 (Right align labels), this causes the section labels on the filtering table to no longer overhang.  It will require a hand fix.

Inside of `_add_simple_filter_controls` (gui_view.py, around line 434), replace the chunk that looks like:

```
        # label the specific section
        tempLabel = add_right_aligned_label(grid_layout, str(file_prefix)+" simple filtering:", current_row)
        #tempLabel.setToolTip("Simple filters are applied after any complex filters are resolved.") # TODO need to specify this once there are complex filters
        tempLabel.setToolTip("Simple filters that will be applied to the data before display or analysis.")
        grid_layout.addWidget(tempLabel, current_row, 0, 1, 2)
```

with

```
        # label the specific section
        tempLabel = QtGui.QLabel(str(file_prefix)+" simple filtering:")
        #tempLabel.setToolTip("Simple filters are applied after any complex filters are resolved.") # TODO need to specify this once there are complex filters
        tempLabel.setToolTip("Simple filters that will be applied to the data before display or analysis.")
        grid_layout.addWidget(tempLabel, current_row, 0, 1, 2)
```

**Comment by evas-ssec** [comment]
I think your window does not look like what I see on my machine to start with, so I'm hesitant to incorporate the changes without some discussion and comparison.

**Comment by adesmet-ssec** [comment]
Per our discussion, the column with "Display Plot" now stretches, so it grows larger as the window is stretched.

Minimum size:


Expanded:


Is it now suitable for merge?

**Comment by adesmet-ssec** [comment]
Migrated to https://gitlab.ssec.wisc.edu/evas/UW-Glance/merge_requests/1

**Pull request closed without merging**
